################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
APP/ap \
APP/ap/modules/cam/RGB_Cam \
APP/ap/modules/cam/thermal_Cam \
APP/ap/modules/common/cli \
APP/ap/modules/display/lvgl \
APP/common/src \
APP/common/src/lcd \
APP/hw \
APP/hw/src \
APP/hw/src/lvgl \
APP/lib/lvgl/src/core \
APP/lib/lvgl/src/display \
APP/lib/lvgl/src/draw \
APP/lib/lvgl/src/draw/nxp/pxp \
APP/lib/lvgl/src/draw/nxp/vglite \
APP/lib/lvgl/src/draw/renesas/dave2d \
APP/lib/lvgl/src/draw/sdl \
APP/lib/lvgl/src/draw/sw/blend/helium \
APP/lib/lvgl/src/draw/sw/blend \
APP/lib/lvgl/src/draw/sw/blend/neon \
APP/lib/lvgl/src/draw/sw \
APP/lib/lvgl/src/draw/vg_lite \
APP/lib/lvgl/src/drivers/display/drm \
APP/lib/lvgl/src/drivers/display/fb \
APP/lib/lvgl/src/drivers/display/ili9341 \
APP/lib/lvgl/src/drivers/display/lcd \
APP/lib/lvgl/src/drivers/display/renesas_glcdc \
APP/lib/lvgl/src/drivers/display/st7735 \
APP/lib/lvgl/src/drivers/display/st7789 \
APP/lib/lvgl/src/drivers/display/st7796 \
APP/lib/lvgl/src/drivers/display/tft_espi \
APP/lib/lvgl/src/drivers/evdev \
APP/lib/lvgl/src/drivers/glfw \
APP/lib/lvgl/src/drivers/libinput \
APP/lib/lvgl/src/drivers/nuttx \
APP/lib/lvgl/src/drivers/qnx \
APP/lib/lvgl/src/drivers/sdl \
APP/lib/lvgl/src/drivers/wayland \
APP/lib/lvgl/src/drivers/windows \
APP/lib/lvgl/src/drivers/x11 \
APP/lib/lvgl/src/font \
APP/lib/lvgl/src/indev \
APP/lib/lvgl/src/layouts/flex \
APP/lib/lvgl/src/layouts/grid \
APP/lib/lvgl/src/layouts \
APP/lib/lvgl/src/libs/barcode \
APP/lib/lvgl/src/libs/bin_decoder \
APP/lib/lvgl/src/libs/bmp \
APP/lib/lvgl/src/libs/ffmpeg \
APP/lib/lvgl/src/libs/freetype \
APP/lib/lvgl/src/libs/fsdrv \
APP/lib/lvgl/src/libs/gif \
APP/lib/lvgl/src/libs/libjpeg_turbo \
APP/lib/lvgl/src/libs/libpng \
APP/lib/lvgl/src/libs/lodepng \
APP/lib/lvgl/src/libs/lz4 \
APP/lib/lvgl/src/libs/qrcode \
APP/lib/lvgl/src/libs/rle \
APP/lib/lvgl/src/libs/rlottie \
APP/lib/lvgl/src/libs/thorvg \
APP/lib/lvgl/src/libs/tiny_ttf \
APP/lib/lvgl/src/libs/tjpgd \
APP/lib/lvgl/src \
APP/lib/lvgl/src/misc/cache \
APP/lib/lvgl/src/misc \
APP/lib/lvgl/src/osal \
APP/lib/lvgl/src/others/file_explorer \
APP/lib/lvgl/src/others/fragment \
APP/lib/lvgl/src/others/gridnav \
APP/lib/lvgl/src/others/ime \
APP/lib/lvgl/src/others/imgfont \
APP/lib/lvgl/src/others/monkey \
APP/lib/lvgl/src/others/observer \
APP/lib/lvgl/src/others/snapshot \
APP/lib/lvgl/src/others/sysmon \
APP/lib/lvgl/src/others/vg_lite_tvg \
APP/lib/lvgl/src/stdlib/builtin \
APP/lib/lvgl/src/stdlib/clib \
APP/lib/lvgl/src/stdlib \
APP/lib/lvgl/src/stdlib/micropython \
APP/lib/lvgl/src/stdlib/rtthread \
APP/lib/lvgl/src/themes/default \
APP/lib/lvgl/src/themes \
APP/lib/lvgl/src/themes/mono \
APP/lib/lvgl/src/themes/simple \
APP/lib/lvgl/src/tick \
APP/lib/lvgl/src/widgets/animimage \
APP/lib/lvgl/src/widgets/arc \
APP/lib/lvgl/src/widgets/bar \
APP/lib/lvgl/src/widgets/button \
APP/lib/lvgl/src/widgets/buttonmatrix \
APP/lib/lvgl/src/widgets/calendar \
APP/lib/lvgl/src/widgets/canvas \
APP/lib/lvgl/src/widgets/chart \
APP/lib/lvgl/src/widgets/checkbox \
APP/lib/lvgl/src/widgets/dropdown \
APP/lib/lvgl/src/widgets/image \
APP/lib/lvgl/src/widgets/imagebutton \
APP/lib/lvgl/src/widgets/keyboard \
APP/lib/lvgl/src/widgets/label \
APP/lib/lvgl/src/widgets/led \
APP/lib/lvgl/src/widgets/line \
APP/lib/lvgl/src/widgets/list \
APP/lib/lvgl/src/widgets/lottie \
APP/lib/lvgl/src/widgets/menu \
APP/lib/lvgl/src/widgets/msgbox \
APP/lib/lvgl/src/widgets/objx_templ \
APP/lib/lvgl/src/widgets/property \
APP/lib/lvgl/src/widgets/roller \
APP/lib/lvgl/src/widgets/scale \
APP/lib/lvgl/src/widgets/slider \
APP/lib/lvgl/src/widgets/span \
APP/lib/lvgl/src/widgets/spinbox \
APP/lib/lvgl/src/widgets/spinner \
APP/lib/lvgl/src/widgets/switch \
APP/lib/lvgl/src/widgets/table \
APP/lib/lvgl/src/widgets/tabview \
APP/lib/lvgl/src/widgets/textarea \
APP/lib/lvgl/src/widgets/tileview \
APP/lib/lvgl/src/widgets/win \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \

